import { Activity, AlertTriangle, ArrowDownToLine, CarFront, CircleGauge, Clock3, RefreshCw, Route, Users } from 'lucide-react'
import { Area, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { mediaUrl } from '../api'
import type { Results } from '../types'
import { MetricCard } from './MetricCard'

const VEHICLE_COLORS = ['#b4ff00','#1ed2dc','#ff8c14','#a874ff','#ffdc00','#f476a8']
const formatTime=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,'0')}:${Math.floor(seconds%60).toString().padStart(2,'0')}`
export function Dashboard({data,onReset}:{data:Results;onReset:()=>void}) {
  const totalVehicles=Object.entries(data.vehicle_counts).filter(([k])=>k!=='person').reduce((sum,[,v])=>sum+v,0)
  const observed=data.congestion.observed.map(p=>({minute:Math.round((p.timestamp_sec||0)/60*10)/10,observed:p.score}))
  const duration=(data.video_meta.duration_sec||0)/60
  const predicted=data.congestion.predicted_trend.map(p=>({minute:Math.round((duration+(p.t_minutes||0))*10)/10,predicted:p.score}))
  const bridge={minute:Math.round(duration*10)/10,predicted:data.congestion.current_score}
  const chartData=[...observed,...[bridge,...predicted]]
  const counts=Object.entries(data.vehicle_counts).map(([name,value])=>({name:name[0].toUpperCase()+name.slice(1),value}))
  return <main className="dashboard">
    <header className="dash-header"><div><span className="live-dot"/> ANALYSIS COMPLETE <span className="job-id">JOB / {data.job_id.toUpperCase()}</span></div><div className="header-actions"><a href={mediaUrl(data.media.metrics_url)}><ArrowDownToLine size={16}/> Export CSV</a><button onClick={onReset}><RefreshCw size={15}/> New analysis</button></div></header>
    <section className="dash-title"><div><span className="eyebrow">Traffic intelligence report</span><h1>Road flow, decoded.</h1></div><div className={`status-chip level-${data.congestion.current_level.toLowerCase().replace(' ','-')}`}><span/><small>Current state</small><strong>{data.congestion.current_level}</strong></div></section>
    <section className="metrics-grid">
      <MetricCard icon={CarFront} label="Vehicles counted" value={totalVehicles.toLocaleString()} detail={`${data.vehicle_counts.car||0} cars · ${data.vehicle_counts.motorcycle||0} motorcycles`}/>
      <MetricCard icon={Users} label="Pedestrians" value={(data.vehicle_counts.person||0).toLocaleString()} detail="Privacy filter applied" tone="cyan"/>
      <MetricCard icon={CircleGauge} label="Average speed" value={`${data.speed.avg_kmh.toFixed(1)}`} detail="km/h · camera estimate" tone="orange"/>
      <MetricCard icon={Activity} label="Congestion index" value={`${Math.round(data.congestion.current_score)}`} detail="out of 100 · rolling score" tone="purple"/>
    </section>
    <section className="dash-grid main-grid">
      <article className="panel video-panel"><PanelHead index="01" title="Annotated feed" meta={`${data.video_meta.resolution} · ${data.video_meta.fps} FPS`}/><video controls playsInline src={mediaUrl(data.media.video_url)}/><div className="video-footer"><span><i/> {data.video_meta.detector.toUpperCase()} DETECTOR</span><span>{data.video_meta.frames_processed.toLocaleString()} FRAMES</span><span>{data.video_meta.avg_inference_ms} MS / INFERENCE</span></div></article>
      <article className="panel trend-panel"><PanelHead index="02" title="Congestion trajectory" meta="5 MIN FORECAST"/><div className="forecast-callout"><span>Predicted in 5 min</span><strong>{data.congestion.predicted_trend.at(-1)?.score.toFixed(0)}</strong><small>/ 100</small></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{top:12,right:12,left:-24,bottom:0}}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b4ff00" stopOpacity={.18}/><stop offset="1" stopColor="#b4ff00" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#202626"/><XAxis dataKey="minute" tickFormatter={v=>`${v}m`} stroke="#66706d" tickLine={false}/><YAxis domain={[0,100]} stroke="#66706d" tickLine={false}/><Tooltip contentStyle={{background:'#111515',border:'1px solid #2a3331',borderRadius:8}}/><Area type="monotone" dataKey="observed" stroke="#b4ff00" strokeWidth={2} fill="url(#area)" connectNulls/><Line type="monotone" dataKey="predicted" stroke="#1ed2dc" strokeWidth={2} strokeDasharray="6 5" dot={{fill:'#1ed2dc',r:3}} connectNulls/></ComposedChart></ResponsiveContainer></div><div className="legend"><span><i className="observed"/> Observed</span><span><i className="predicted"/> Linear trend forecast</span></div></article>
    </section>
    <section className="dash-grid detail-grid">
      <article className="panel"><PanelHead index="03" title="Road user mix"/><div className="bar-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={counts} margin={{left:-25,right:5}}><CartesianGrid vertical={false} stroke="#202626"/><XAxis dataKey="name" stroke="#66706d" tickLine={false}/><YAxis stroke="#66706d" tickLine={false}/><Tooltip cursor={{fill:'#161b1a'}} contentStyle={{background:'#111515',border:'1px solid #2a3331',borderRadius:8}}/><Bar dataKey="value" radius={[3,3,0,0]}>{counts.map((_,i)=><Cell key={i} fill={VEHICLE_COLORS[i%VEHICLE_COLORS.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></article>
      <article className="panel lane-panel"><PanelHead index="04" title="Lane pressure" meta="LIVE SNAPSHOT"/><div className="lane-table"><div className="lane-row head"><span>Approach</span><span>Volume</span><span>Avg speed</span><span>Pressure</span></div>{data.lanes.map(l=><div className="lane-row" key={l.lane}><span><b>{l.lane.toString().padStart(2,'0')}</b> Lane {l.lane}</span><span>{l.count}</span><span>{l.avg_speed_kmh.toFixed(1)} km/h</span><span><i style={{width:`${Math.min(100,l.count/Math.max(...data.lanes.map(x=>x.count),1)*100)}%`}}/></span></div>)}</div></article>
      <article className="panel signal-panel"><PanelHead index="05" title="Signal recommendation"/><div className="signal-body"><div className="signal-glyph"><span/><span className="active"/><span/></div><div><span className="eyebrow">Recommended phase</span><h3>{data.signal_recommendation.phase.replaceAll('_',' ')}</h3><p>{data.signal_recommendation.reason}</p></div><div className="green-time"><strong>{data.signal_recommendation.green_time_sec}</strong><span>seconds<br/>green time</span></div></div></article>
    </section>
    <section className="dash-grid media-grid"><article className="panel snapshot"><PanelHead index="06" title="Flow density" meta="HEATMAP"/><img src={mediaUrl(data.media.heatmap_url)} alt="Traffic density heatmap"/></article><article className="panel snapshot"><PanelHead index="07" title="Spatial projection" meta="TOP-DOWN · NOT HOMOGRAPHY"/><img src={mediaUrl(data.media.bev_url)} alt="Top-down traffic projection"/></article><article className="panel incidents"><PanelHead index="08" title="Detected events" meta={`${data.incidents.length} ALERTS`}/><div className="incident-list">{data.incidents.length?data.incidents.map((item,i)=><div key={i}><span className="alert-icon"><AlertTriangle size={16}/></span><div><strong>{item.type.replace('_',' ')}</strong><small>Track #{item.track_id} · Lane {item.lane}</small></div><time><Clock3 size={13}/>{formatTime(item.timestamp_sec)}</time></div>):<div className="all-clear"><Route size={25}/><strong>No incidents detected</strong><small>Traffic flow remained within expected movement thresholds.</small></div>}</div></article></section>
    <footer><span>PULSEWAY TRAFFIC INTELLIGENCE</span><span>Speed values require per-camera calibration for enforcement-grade measurement.</span></footer>
  </main>
}
function PanelHead({index,title,meta}:{index:string;title:string;meta?:string}){return <div className="panel-head"><div><span>{index}</span><h2>{title}</h2></div>{meta&&<small>{meta}</small>}</div>}
